Repository rubyists/dapr-ruby-client, pull requests merged in 2024-10, with the labels that each got.

#72 fix(lock): Updates lock/unlock to append _alpha1
  coverage/coverage.json
  lib/dapr/client/lock.rb
  test/dapr/client/test_lock.rb
Labels: bug

#73 chore(main): release 0.3.3
  .release-please-manifest.json
  .version.txt
  CHANGELOG.md
  lib/dapr/version.rb
Labels: autorelease: pending

#74 feat(state)!: Adds state management component
  coverage/coverage.json
  lib/dapr/client.rb
  lib/dapr/client/state.rb
  test/dapr/client/test_state.rb
Labels: enhancement

#75 chore(main): release 0.4.0
  .release-please-manifest.json
  .version.txt
  CHANGELOG.md
  lib/dapr/version.rb
Labels: autorelease: pending

#77 chore(main): release 0.4.1
  .release-please-manifest.json
  .version.txt
  CHANGELOG.md
  lib/dapr/version.rb
Labels: autorelease: pending
